### ISSUE TITLE
Optimise background images for breakpoints

### ISSUE THREAD

**Issue by LiamOSullivan** [BuildingCityDashboards/bcd-dd-v2.1#1076]
related #1054

**Comment by CC-Claire** [comment]
@LiamOSullivan Background images (svgs+ pngs) for Tablet and Mobile breakpoints have been to the Background images folder here:

- https://github.com/BuildingCityDashboards/bcd-dd-v2.1/tree/staging/docs/BCD-Design/Media/Backgrounds/Themes_Tablet

- https://github.com/BuildingCityDashboards/bcd-dd-v2.1/tree/staging/docs/BCD-Design/Media/Backgrounds/Themes_Mobile
