### ISSUE TITLE
Search bar portal link

### ISSUE THREAD

**Issue by LiamOSullivan** [BuildingCityDashboards/bcd-dd-v2.1#1097]
We need a mockup of how the link to the Portal page will work e.g. with the searchbar across pages and/or on the homepage only etc.

**Comment by CC-Claire** [comment]
Portal link stays persistent across all pages, as above it mimics the search bar appearing on all pages in top right hand corner.

Mockup (Zeplin plugin is down but will upload there when I can):
- ![Portal Icon Placement](https://user-images.githubusercontent.com/57443304/83529481-4e36cd80-a4e2-11ea-98bc-d89b2fbf750e.png)


Icon link:
- https://github.com/BuildingCityDashboards/bcd-dd-v2.1/blob/staging/docs/BCD-Design/Icons/Icons_24px/portal_icon.svg
