### ISSUE TITLE
Plots fail to load on iPhone

### ISSUE THREAD

**Issue by samstehle** [BuildingCityDashboards/bcd-dd-v2.1#1229]
A number of plots on the themes page do not appear on mobile. 

Using iPhone 7 Chrome + Safari (same effect), 1,334 x 750 px

Missing plots: public transport usage, traffic counters, noise level monitoring, employment by sector, number of employees by size of company, gross value added per person at basic prices, dublin airport passengers arrival numbers, dublin port tonnage, pupil numbers, households in dublin, households by number of persons (2016). The rest appear ok.

 (also note the darker text above TrafficCounters)

![iPhone_NoPlot2](https://user-images.githubusercontent.com/5630150/87177927-6d2b3b00-c2aa-11ea-8b2f-35eff79253b1.png)
![iPhone_NoPlot](https://user-images.githubusercontent.com/5630150/87177930-6d2b3b00-c2aa-11ea-8156-4ef54119038b.png)

Some plots are ok, however, for example
![iPhone_SomePlotsOK](https://user-images.githubusercontent.com/5630150/87178047-9946bc00-c2aa-11ea-95e5-1e6bfb6e206d.png)

**Comment by samstehle** [comment]
Also includes data stories page - all plots fail to display on iPhone 7 Chrome and Safari:

![6FFD7121-E85C-431A-9997-BE4408767386](https://user-images.githubusercontent.com/5630150/87178726-9c8e7780-c2ab-11ea-8da0-4a3870fa7236.png)

**Comment by LiamOSullivan** [comment]
This is possibly due to use of ES6 modules-> need fallbacks

**Comment by LiamOSullivan** [comment]
Issue fixed by PR #1242 

Some individual chart bugs remain
