### ISSUE TITLE
Home pages carousels need more padding 

### ISSUE THREAD

**Issue by samstehle** [BuildingCityDashboards/bcd-dd-v2.1#1231]
New home pages are hard to interact with, e.g. to flip through multiple queries from the carousel. 

iPhone 7 on Chrome and Safari, 1334 x 750 px resolution

Swiping does not flip to the next card, but the arrow overflows the page: 

![5D61CCBA-156D-4C65-96A8-1DC3A89E4040](https://user-images.githubusercontent.com/5630150/87179654-12dfa980-c2ad-11ea-9bc9-5ed7deb2d918.png)

Moving the whole page horizontally a touch will expose the arrow:

![49C464ED-C690-4AEA-BDB4-0168FF50DACA](https://user-images.githubusercontent.com/5630150/87179687-23901f80-c2ad-11ea-91c3-aaa8f2c3de28.png)

**Comment by LiamOSullivan** [comment]
Fixed margins, but swiping still doesn't work. Card advance via arrow only
