### ISSUE TITLE
Themes headers > add scroll arrow

### ISSUE THREAD

**Issue by LiamOSullivan** [BuildingCityDashboards/bcd-dd-v2.1#1264]
Create a scroll arrow on each of the Themes header/ hero pages to indicate to users that the charts are below

<img width="1541" alt="Screenshot 2020-08-05 at 10 49 07" src="https://user-images.githubusercontent.com/3306019/89398685-5b05b680-d709-11ea-9447-792ce2303b99.png">

<img width="810" alt="Screenshot 2020-08-05 at 10 47 51" src="https://user-images.githubusercontent.com/3306019/89398655-4e815e00-d709-11ea-9a5e-9731dc8a3f61.png">

**Comment by CC-Claire** [comment]
Arrow icon here if needed:
docs/BCD-Design/Icons/Icons_24px/arrow_down.svg
