### ISSUE TITLE
Themes > Labour force chart data not updating

### ISSUE THREAD

**Issue by LiamOSullivan** [BuildingCityDashboards/bcd-dd-v2.1#1301]
Following the link to the CSO table shows data to 2020Q1, but chart only to 2019Q4

<img width="437" alt="Screenshot 2020-07-30 at 15 11 01" src="https://user-images.githubusercontent.com/3306019/88933212-067cba00-d277-11ea-946a-50f524292b06.png">

**Comment by LiamOSullivan** [comment]
This still uses static data, need to use statbank table QLF08

The code pattern to read and display this data can be found [here](https://github.com/BuildingCityDashboards/bcd-cd-v2.0/blob/ecdfd5442d5c5e1027e309573ae57aedafbbee9d/public/javascripts/themes/economy/economy_employment.js) with the view [here](https://github.com/BuildingCityDashboards/bcd-cd-v2.0/blob/ecdfd5442d5c5e1027e309573ae57aedafbbee9d/views/themes/theme_economy.pug)

**Comment by LiamOSullivan** [comment]
This has been fixed on the Cork Dashboard, port the code from the links in the above comment

**Comment by BashirShalaik** [comment]
This chart is generated when applying QLF08 data to Multiline chart , and it did not show chart when trying to use  StackedArea. 

<img width="1261" alt="Screen Shot 2020-09-23 at 17 13 22" src="https://user-images.githubusercontent.com/50174872/94040893-6730fa80-fdc1-11ea-8726-a1c5ee34eba5.png">

**Comment by LiamOSullivan** [comment]
Is there a branch for this Bashir?
