### ISSUE TITLE
Tablet resolution needs layout fix

### ISSUE THREAD

**Issue by LiamOSullivan** [BuildingCityDashboards/bcd-dd-v2.1#1316]
![image](https://user-images.githubusercontent.com/3306019/89537916-db9fe200-d7f1-11ea-95a5-91cbb403b314.png)

**Comment by CC-Claire** [comment]
@BashirShalaik  Zeplin link here:

https://zpl.io/29W1lWB

I added screens for portrait + landscape as I envision the side by side not working on portrait so it effectively works as per mobile; the graph slots underneath the text box instead of side by side. Any problems let me know
