### ISSUE TITLE
Queries Page is not shown on small devices

### ISSUE THREAD

**Issue by BashirShalaik** [BuildingCityDashboards/bcd-dd-v2.1#1317]
<img width="385" alt="Screen Shot 2020-08-06 at 15 25 02" src="https://user-images.githubusercontent.com/50174872/89543969-794adf80-d7f9-11ea-9d64-7687650c23aa.png">

**Comment by LiamOSullivan** [comment]
This is still happening when linking e.g. from footer at screen width of <1280px
