### ISSUE TITLE
Stories > Housing Part 1 - page composition needs review

### ISSUE THREAD

**Issue by LiamOSullivan** [BuildingCityDashboards/bcd-dd-v2.1#155]
Explore use of 'scrollytelling'

**Comment by CC-Claire** [comment]
Prototype of single scroll (with view to expanding to a dual scroll): https://www.figma.com/proto/u1AuOz6VqJ0i6WxcLZLUC4/BCD-Design-System-In-Progress?node-id=380%3A1&scaling=scale-down-width

**Comment by CC-Claire** [comment]
Zeplin links for...

Web Content Layout:

- https://zpl.io/VKZ78JA

Hero Pages for Housing 1-3:

- https://zpl.io/2pGRewr
