### ISSUE TITLE
Update DDv2 Unemployment Quarterly Count

### ISSUE THREAD

**Issue by virtualarchitectures** [BuildingCityDashboards/bcd-dd-v2.1#179]
Update Unemployment Quarterly Count
Page: https://dublindashboard-beta.azurewebsites.net/
Title: Unemployment Quarterly Count
Source: CSO Statbank - https://statbank.cso.ie/px/pxeirestat/Statire/SelectVarVal/Define.asp?maintable=QLF08&PLanguage=0

**Comment by virtualarchitectures** [comment]
Older data in existing table appeared erroneous. Agreed to use validated Statbank data from 2012 onward. Automated processing from Statbank API in Jupyter notebook at following location: https://github.com/virtualarchitectures/BCD_Dashboard_Table_Preparation Manual data preparation steps also documented. Data provided from 2012Q1 to 2019Q2. Completed (20/09/2019).

**Comment by virtualarchitectures** [comment]
Dev team to update data on Dashboard

**Comment by LiamOSullivan** [comment]
Downloaded from table as public/data/Economy/downloaded/20201151623314889086QLF0859640977923.csv

**Comment by LiamOSullivan** [comment]
Processed to public/data/Economy/processed/unemployment_quarterly_dublin.csv
