### ISSUE TITLE
Update DDv2 Monthly Property Price Index

### ISSUE THREAD

**Issue by virtualarchitectures** [BuildingCityDashboards/bcd-dd-v2.1#181]
Title: Monthly Property Price Index
Page: https://dublindashboard-beta.azurewebsites.net/
Source: CSO Statbank - https://www.cso.ie/px/pxeirestat/Statire/SelectVarVal/Define.asp?maintable=HPM06&PLanguage=0

**Comment by virtualarchitectures** [comment]
Data provided from Jan 2005 to Aug 2019. Data uploaded to repo (bcd-dd-v2.1/public/data/Housing/) Manual data preparation steps also documented. Completed (06/11/2019).

**Comment by virtualarchitectures** [comment]
Dev team to update data on dashboard

**Comment by LiamOSullivan** [comment]
2 tasks here
1- add new data to appropriate charts
2 - automate Olly's process server-side to periodically fetch new data

**Comment by LiamOSullivan** [comment]
Data integrated onto card up to Aug-19
