### ISSUE TITLE
Update DDv2 Monthly House Unit Completions

### ISSUE THREAD

**Issue by virtualarchitectures** [BuildingCityDashboards/bcd-dd-v2.1#183]
Title: Monthly House Unit Completions
Page: https://dublindashboard-beta.azurewebsites.net/
Source: Department of Housing Planning and Local Government - https://www.housing.gov.ie/housing/statistics/house-building-and-private-rented/construction-activity-esb-connections

**Comment by virtualarchitectures** [comment]
Data available in two locations:
Department of Housing, Planning and Local Government - https://www.housing.gov.ie/housing/statistics/house-building-and-private-rented/construction-activity-esb-connections

CSO Statbank - https://statbank.cso.ie/px/pxeirestat/Database/eirestat/Housing%20Statistics/Housing%20Statistics_statbank.asp?SP=Housing%20Statistics&Planguage=0&ProductID=DB_HS

First looks suggests data appears discontinuous in each. Unclear whether DHPLG is actively maintained and suggests CSO is authoritative.

**Comment by virtualarchitectures** [comment]
DHPLG reporting on ESB collections ended in early 2018. New dwelling completions (NDC) is now reported by the CSO as documented here: https://www.cso.ie/en/releasesandpublications/ep/p-ndc/newdwellingcompletionsq12018/
The closest dataset to existing stats in the original dashboard is quarterly report NDQ05 from 2011 to present:
https://statbank.cso.ie/px/pxeirestat/Statire/SelectVarVal/Define.asp?maintable=NDQ05&PLanguage=0

**Comment by virtualarchitectures** [comment]
Data provided from 2011Q1 to 2019Q2. Data uploaded to repo (bcd-dd-v2.1/public/data/Housing/) Manual data preparation steps also documented. Completed (13/11/2019).

Note: File replaces 'construction monthlies.csv' which contained values based on ESB. New figures are generally higher.

**Comment by virtualarchitectures** [comment]
Dev team to update data on dashboard

**Comment by LiamOSullivan** [comment]
Downloaded data from NDQ05: New Dwelling Completion by Local Authority and Quarter to public/data/Housing/downloaded/20201161053914897483NDQ0539304343872.csv

**Comment by LiamOSullivan** [comment]
Processed to public/data/Housing/processed/NDQ05.csv
