### ISSUE TITLE
Maps fail to render properly at highest zoom level

### ISSUE THREAD

**Issue by virtualarchitectures** [BuildingCityDashboards/bcd-dd-v2.1#205]
Map for water quality on the Themes page fails to render at the highest zoom level (tested in Chrome and Firefox)

![image](https://user-images.githubusercontent.com/10799911/68844881-65d37380-06c2-11ea-9dae-2a2cb4939b40.png)

**Comment by LiamOSullivan** [comment]
@BashirShalaik Bashir- as you are working on this could you do a simple fix by clamping the highest zoom level to a robust number? I think zoom of 11 or 12 works well.

We'll need to address this better in the future- the tile server fails to respond with data  but not sure why this is happening? If it just doesn't serve tiles at this zoom (ie. not intermittent) then the suggested quick fix will do. Log file below

[dublindashboard-beta.azurewebsites.net-1573725465414.log](https://github.com/BuildingCityDashboards/bcd-dd-v2.1/files/3845806/dublindashboard-beta.azurewebsites.net-1573725465414.log)

**Comment by BashirShalaik** [comment]
Maximum zoom level was set to 12
