### ISSUE TITLE
Add carpark data to dashboard

### ISSUE THREAD

**Issue by LiamOSullivan** [BuildingCityDashboards/bcd-dd-v2.1#226]

**Comment by virtualarchitectures** [comment]
Data currently accessed via Dublinked: https://data.smartdublin.ie/dataset/multi-story-car-parking-space-availability

This provides links to two resources:
- Official XML link: http://opendata.dublincity.ie/TrafficOpenData/CP_TR/CPDATA.xml [Data missing and several days lag from last reporting]
- Derilinx 3D Hackathon version: http://www.dublincity.ie/dublintraffic/carparks.htm [404 Error]

Derilinx contacted 06/12/2019 and indicated issue would require prioritisation by SmartDublin.

**Comment by virtualarchitectures** [comment]
Carpark data seems to be working. Use the Official XML link: http://opendata.dublincity.ie/TrafficOpenData/CP_TR/CPDATA.xml 

Note: Data Updates every 5 mins or so. The endpoint reports a numeric value for available spaces or else either "FULL" or a blank value " ".

Data about the location are held in the `cpCaps.json` which I believe was prepared by the BCD team. The file has a nested structure which was problematic to parse in C#. As the file is believed to have been created our team I prepared a new flatter version of the file: cpCAPS_RESTRUCTURED.json. The file includes a count of Total Spaces which I believed has been scrapped from the car parks operators websites (e.g. QPARK: https://www.q-park.ie/en-gb/cities/dublin/ ). The number of available spaces reported by the API has been shown to exceed the number of total spaces.

Recommend just displaying available spaces as reported by the API.

**Comment by virtualarchitectures** [comment]
Closing ticket as data feed currently available from API.
