### ISSUE TITLE
Stories > housing- images are lo res

### ISSUE THREAD

**Issue by LiamOSullivan** [BuildingCityDashboards/bcd-dd-v2.1#345]
Replace with better quality images w/ breakpoint versions

**Comment by CC-Claire** [comment]
@LiamOSullivan  Added to docs folder:

Web:
- https://github.com/BuildingCityDashboards/bcd-dd-v2.1/tree/staging/docs/BCD-Design/Media/Backgrounds/Stories_Web

Tablet:
- https://github.com/BuildingCityDashboards/bcd-dd-v2.1/tree/staging/docs/BCD-Design/Media/Backgrounds/Stories_Tablet

Mobile:
- https://github.com/BuildingCityDashboards/bcd-dd-v2.1/tree/staging/docs/BCD-Design/Media/Backgrounds/Stories_Mobile
