### ISSUE TITLE
UX: Add differentiating colours to 4 Local Authorities

### ISSUE THREAD

**Issue by CC-Claire** [BuildingCityDashboards/bcd-dd-v2.1#401]
Survey: Minor
UI - Colour
- Add differentiating colours to 4 Local Authorities

From Dashboard survey:
- Hard to differentiate between the 4 Las

**Comment by LiamOSullivan** [comment]
RK: Gold for DL-R doesn't work on scrolly story.
Do we have a fixed colorway for LAs site-wide?

See below: white text on bars with black background doesn't work well on light coloured bars

<img width="659" alt="Screenshot 2020-06-24 at 09 42 10" src="https://user-images.githubusercontent.com/3306019/85523549-085fb780-b5ff-11ea-9fae-e74c4d72f47e.png">

**Comment by CC-Claire** [comment]
Updated Colour scheme here with a little explainer:

https://zpl.io/bAoln6q
