### ISSUE TITLE
Mobile mock-ups for About Dublin

### ISSUE THREAD

**Issue by LiamOSullivan** [BuildingCityDashboards/bcd-dd-v2.1#592]
Currently the map is hidden on mobile and replaced with buttons. Continue with this (design review required) or re-design?

<img width="612" alt="Screen Shot 2020-02-11 at 11 11 00" src="https://user-images.githubusercontent.com/3306019/74231794-51057c80-4cbf-11ea-83bf-87f096809eab.png">

**Comment by CC-Claire** [comment]
I've been working on some mockups of this with the map included. I'll add in here for you to take a look at and see if it could work.

**Comment by LiamOSullivan** [comment]
Final implementation this date
