### ISSUE TITLE
New background hero image required

### ISSUE THREAD

**Issue by LiamOSullivan** [BuildingCityDashboards/bcd-dd-v2.1#593]
As per mockups

**Comment by CC-Claire** [comment]
Hero Image link here: https://github.com/BuildingCityDashboards/bcd-dd-v2.1/tree/staging/docs/BCD-Design/Media

**Comment by CC-Claire** [comment]
Hero image cut off on second section of homepage
![Background photo](https://user-images.githubusercontent.com/57443304/77310043-8c9b5980-6cf5-11ea-90cf-a8806a20a698.png)
