### ISSUE TITLE
Stories > Use new template for housing story

### ISSUE THREAD

**Issue by LiamOSullivan** [BuildingCityDashboards/bcd-dd-v2.1#595]
As per https://github.com/BuildingCityDashboards/bcd-dd-v2.1/blob/staging/docs/housing_story_content/Data%20stories.pptx

**Comment by LiamOSullivan** [comment]
AIRO example: https://storymaps.arcgis.com/stories/3541fb378c5345bcb63f9b2484fcf399

**Comment by samstehle** [comment]
Is the primary enhancement here over the current housing story design the AIRO addition of scrolly text beside the map portions of the story? I don't otherwise see any significant differences

**Comment by LiamOSullivan** [comment]
We basically want to break up the 'wall of text' and move closer to the format of an actual data story, rather than a textual narrative with supporting charts. Presenting the data in bite-sized chunks (via a stepped/scrolling interaction) is desirable, as is providing multiple contexts for the same data (chart stays on screen and annotations, context text changes for example).
