### ISSUE TITLE
Card state change not working on hover/click

### ISSUE THREAD

**Issue by CC-Claire** [BuildingCityDashboards/bcd-dd-v2.1#717]
Implement card state change on hover and select (colour and border change).

- Currently card is expanding on hover to show description text but colour change is not happening, also an issue with state change on click.

Recorded at 1920 x 1080
Chrome - Windows

Issue:
![card state change on hover and select](https://user-images.githubusercontent.com/57443304/77316383-3f24e980-6d01-11ea-9dca-8500fd508da3.png)

Mockups:
https://zpl.io/ad0YQNR

**Comment by LiamOSullivan** [comment]
Need to add border at higher > 1280px res
