### ISSUE TITLE
About Dublin card is cut off + change dimensions

### ISSUE THREAD

**Issue by CC-Claire** [BuildingCityDashboards/bcd-dd-v2.1#719]
1. The About Dublin card is cut off, hiding text below cut off point.
2. Restructure layout to allow map to increase in size vertically, pushing About Dublin card left

Recorded at 1920 x 1080
Chrome - Windows

Issue:

1. Cutting off text
![Card cut off](https://user-images.githubusercontent.com/57443304/77319907-8b732800-6d07-11ea-9d4e-0f6df2c4cbd2.png)

2. Layout restructure
![Layout restructure](https://user-images.githubusercontent.com/57443304/77319921-8f9f4580-6d07-11ea-995e-f0d33a3b28fe.png)

Mockups:
https://zpl.io/2vpAe8e
![About Dublin map + card](https://user-images.githubusercontent.com/57443304/77319781-5535a880-6d07-11ea-9598-f90013291ca5.png)

**Comment by LiamOSullivan** [comment]
FIxed commit 7a558651863992333dea6800e650244304b00ccd
