### ISSUE TITLE
Call to action to select map appears condensed + add arrow

### ISSUE THREAD

**Issue by CC-Claire** [BuildingCityDashboards/bcd-dd-v2.1#720]
Lengthen call to action to select map so it is all on one line + add arrow after pointing to map.

Recorded at 1920 x 1080
Chrome - Windows

Issue:
![call to action condensed](https://user-images.githubusercontent.com/57443304/77320361-56b3a080-6d08-11ea-8779-16baea02a780.png)

Mockup:
![About Dublin map + card](https://user-images.githubusercontent.com/57443304/77320309-3be12c00-6d08-11ea-97fa-44fc0ad7e4eb.png)

**Comment by LiamOSullivan** [comment]
Leaving the About Dublin section full width for now
