### ISSUE TITLE
Left align pop up LA card to About Dublin card

### ISSUE THREAD

**Issue by CC-Claire** [BuildingCityDashboards/bcd-dd-v2.1#721]
LA card that appears on click of map is indented, Left align this pop up LA card to the About Dublin card.

Recorded on 1920 x 1080
Chrome - Windows

Issue:
![Left align pop up card to About Dublin card](https://user-images.githubusercontent.com/57443304/77320610-cc1f7100-6d08-11ea-959b-8d3dbc9478db.png)

Mockup:
https://zpl.io/bAyDYmn
![About Dublin_Selected](https://user-images.githubusercontent.com/57443304/77320980-64b5f100-6d09-11ea-9f49-1fa71b861d85.png)

**Comment by LiamOSullivan** [comment]
Fix commit 7a558651863992333dea6800e650244304b00ccd
