### ISSUE TITLE
About Dashboard card cut off

### ISSUE THREAD

**Issue by CC-Claire** [BuildingCityDashboards/bcd-dd-v2.1#724]
About Dashboard card is cut off at bottom, allow for card to house all text without scrolling inside card.

Recorded at 1920 x 1080

Issue:
![About Dashboard card cut off](https://user-images.githubusercontent.com/57443304/77329755-57ebca00-6d16-11ea-96e0-3bcdffacddf9.png)

**Comment by LiamOSullivan** [comment]
Can't recreate this, I get this. Can you let me know OS + browser?

![Screen Shot 2020-03-23 at 15 01 20](https://user-images.githubusercontent.com/3306019/77330417-3e974d80-6d17-11ea-8d98-ff35b9f9c6b8.png)

**Comment by CC-Claire** [comment]
Sorry its Chrome on Windows

**Comment by CC-Claire** [comment]
Just checked again and I see the double columns now that you see, I was making a note of this issue on Thursday so I think it may have updated since then. What may be more legible though is a single column but the card to increase in size to house the text (not dynamically but to just be bigger as per mockup). I think the font sizes are larger on the site which may be whats causing the overfill, body should be 16px.

**Comment by LiamOSullivan** [comment]
Fixed commit this date, but leaving 2-columns at highest res (1920 px) for now pending user feedback
