### ISSUE TITLE
Font weights and size displaying incorrectly

### ISSUE THREAD

**Issue by CC-Claire** [BuildingCityDashboards/bcd-dd-v2.1#726]
Currently on the About Dublin and About Dashboard cards and titles, the font sizes and weights seem to be displaying incorrectly. It may be an issue with full specs in Figma not translating to Zeplin in which case I can test and return simplified styles.

- The font weights look like they are bold and not "Regular"
- The font sizes look a bit large on site, I had set card titles as 34px and inside card text as 16px. These are trial and error, and may be too small so am happy to change if needs be. But keeping to this size may help layout fixing of About Dublin card and LA map in other issue.

Recorded at 1920 x 1080

Issue:
![Font size and weights](https://user-images.githubusercontent.com/57443304/77331629-ea8d6880-6d18-11ea-98d2-8c6ae6d27c5a.png)
![font size and weights 2](https://user-images.githubusercontent.com/57443304/77331638-ecefc280-6d18-11ea-929b-acb0f5abffd7.png)

Mockups:
https://zpl.io/bAyDYmn
https://zpl.io/VkoZYYq

**Comment by LiamOSullivan** [comment]
Using 'Regular' in CSS doesn't work (prob have to import the font family with that spec) but I've loaded options for weights of 300, 500 and 700. Was using 500 as default for regular weight, but will now use 300.
