### ISSUE TITLE
Redesign UX

### ISSUE THREAD

**Issue by LiamOSullivan** [BuildingCityDashboards/bcd-dd-v2.1#792]

**Comment by CC-Claire** [comment]
Redesign of Geodemographics tool following meeting with Burcin, Bashir, and Liam:

- Header Description added
- Group Description added
- Z Score Summary Analysis added
- UX design for comparing/selecting +deselecting groups
- Overall redesign of UI to align with rest of site

Zeplin link for re-design (includes overview breakdown of components and functionality for comparison): 
- https://zpl.io/VYgONRp

PNGs:
![GeoDemographic_Tool](https://user-images.githubusercontent.com/57443304/82901699-3a292400-9f56-11ea-8fbf-1dda6db744a9.png)
![GeoDemographic_Tool_Scrolled Down](https://user-images.githubusercontent.com/57443304/82901701-3ac1ba80-9f56-11ea-9396-7ab6e5a20cd1.png)
![GeoDemographics_Overview](https://user-images.githubusercontent.com/57443304/82901703-3b5a5100-9f56-11ea-9b24-b8dcf58d5b17.png)
