### ISSUE TITLE
Add card for air quality

### ISSUE THREAD

**Issue by LiamOSullivan** [BuildingCityDashboards/bcd-dd-v2.1#934]
Use a card to indicate the 'Air quality is xxx' message from the old dashboard environment map.

**Comment by samstehle** [comment]
Link to the EPA source for Air Quality Index for Health: 
https://erc.epa.ie/real-time-air/www/aqindex/aqih_json.php

**Comment by LiamOSullivan** [comment]
Implementing for Cork

**Comment by LiamOSullivan** [comment]
Related #1383
