### ISSUE TITLE
Themes > Dark maps?

### ISSUE THREAD

**Issue by LiamOSullivan** [BuildingCityDashboards/bcd-dd-v2.1#966]
Q for CC- are all maps to use dark-view as per the mockups?

**Comment by CC-Claire** [comment]
Plan was initially yes, but not a big deal if not possible or if there is accessibility issues arising from it, as they are their own entity (not on a dark card for example) they can exist as is without a dark implementation on themselves. I think the current state of the maps look good so I think leaving it as this would be fine, and can revisit if people flag it as something that stands out negatively.

**Comment by LiamOSullivan** [comment]
Good, parking this so
