### ISSUE TITLE
Which side-menu presentation is desirable?

### ISSUE THREAD

**Issue by LiamOSullivan** [BuildingCityDashboards/bcd-dd-v2.1#982]
The side menu show different sub-sections based on the current page.

On Home and e.g. Tools: 

<img width="439" alt="Screenshot 2020-05-15 at 13 10 57" src="https://user-images.githubusercontent.com/3306019/82049134-bfd2e700-96ad-11ea-9c02-554fd0692ea9.png">

But on Themes, sections are shown:
<img width="411" alt="Screenshot 2020-05-15 at 13 11 08" src="https://user-images.githubusercontent.com/3306019/82049182-d37e4d80-96ad-11ea-817f-07e2cbcfb8f8.png">

Is this the preferred behaviour?

**Comment by CC-Claire** [comment]
Yes that behaviour looks good, I would have said have the sub menu appear on hover regardless of what page the user is on, but that would not translate to mobile. This looks a good compromise.
