### ISSUE TITLE
Themes > CTA for more

### ISSUE THREAD

**Issue by LiamOSullivan** [BuildingCityDashboards/bcd-dd-v2.1#989]
When naving to e.g. population from the home page card, should there be a cta/down arrow nav to encourage users to scroll to further related charts?

<img width="1250" alt="Screenshot 2020-05-16 at 12 45 32" src="https://user-images.githubusercontent.com/3306019/82119052-31289d80-9773-11ea-9015-21484b1a689b.png">

**Comment by LiamOSullivan** [comment]
This was also suggested in RK's review

**Comment by CC-Claire** [comment]
Yes that sounds wise, I've included it here on the hero page(s) as that will be the first place a user lands once they click Themes. I think it might make more sense there for that reason, but if it is still unclear then it could be added to the first chart in each section too.

Mockup here:
- ![transport_landing_arrow down](https://user-images.githubusercontent.com/57443304/83537472-7c210f80-a4ec-11ea-8d4b-6fb2915eef8c.png)


Arrow Icon:
- https://github.com/BuildingCityDashboards/bcd-dd-v2.1/blob/staging/docs/BCD-Design/Icons/Icons_24px/arrow_down.svg

**Comment by LiamOSullivan** [comment]
Spacing between themes charts used to show content and encourage scrolling
